// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package bw.ub.stripehiv.user.web.edit;

/**
 * @see bw.ub.stripehiv.user.web.edit.UserEditController
 */
public class UserEditControllerImpl
    extends UserEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 2317992786666591403L;

    /**
     * @see bw.ub.stripehiv.user.web.edit.UserEditController#doInitialiseEditScreen(java.lang.Long id)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
    }

    /**
     * @see bw.ub.stripehiv.user.web.edit.UserEditController#doNewUser()
     */
    @Override
    public void doNewUser()
    {
    }

    /**
     * @see bw.ub.stripehiv.user.web.edit.UserEditController#doSaveUser()
     */
    @Override
    public void doSaveUser()
    {
    }

}