// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package bw.ub.stripehiv.module.objective.web.search;

/**
 * @see bw.ub.stripehiv.module.objective.web.search.ObjectiveSearchController
 */
public class ObjectiveSearchControllerImpl
    extends ObjectiveSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1347564954677531703L;

    /**
     * @see bw.ub.stripehiv.module.objective.web.search.ObjectiveSearchController#doInitialiseSearchScreen(bw.ub.stripehiv.module.objective.vo.ObjectiveSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        // populating value with dummy instance
        bw.ub.stripehiv.module.objective.vo.ObjectiveSearchCriteria searchCriteria = new bw.ub.stripehiv.module.objective.vo.ObjectiveSearchCriteria();
        searchCriteria.setCode(null);
        searchCriteria.setModule(null);
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * @see bw.ub.stripehiv.module.objective.web.search.ObjectiveSearchController#doObjectiveSearch()
     */
    @Override
    public void doObjectiveSearch()
    {
    }

    /**
     * @see bw.ub.stripehiv.module.objective.web.search.ObjectiveSearchController#doEditObjective(java.lang.Long id, java.lang.Long objectiveId)
     */
    @Override
    public void doEditObjective(DoEditObjectiveForm form)
    {
    }

    /**
     * This dummy variable is used to populate the "objectives" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final bw.ub.stripehiv.module.objective.vo.ObjectiveVO objectives =
        new bw.ub.stripehiv.module.objective.vo.ObjectiveVO
        {
            new bw.ub.stripehiv.module.objective.vo.ObjectiveVO("code-1", "description-1", null, null),
            new bw.ub.stripehiv.module.objective.vo.ObjectiveVO("code-2", "description-2", null, null),
            new bw.ub.stripehiv.module.objective.vo.ObjectiveVO("code-3", "description-3", null, null),
            new bw.ub.stripehiv.module.objective.vo.ObjectiveVO("code-4", "description-4", null, null),
            new bw.ub.stripehiv.module.objective.vo.ObjectiveVO("code-5", "description-5", null, null)
        };
}