// Generated by andromda-jsf cartridge (view\table\table.component.impl.ts.vsl) DO NOT EDIT!
import { Component, Injector } from '@angular/core';
import { SearchModulesModulesComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/web/search/search-modules-modules.component';

@Component({
  selector: 'search-modules-modules',
  templateUrl: './search-modules-modules.component.html',
  styleUrls: ['./search-modules-modules.component.css']
})
export class SearchModulesModulesImplComponent extends SearchModulesModulesComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

	beforeOnInit(){
	}
	
	afterOnInit() {
	}	

	doSearchModulesEdit(id: number): any {
  }
  
  doNgAfterViewInit() {
  }
}