// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { SearchModulesComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/web/search/search-modules.component';
import { FormArray } from '@angular/forms';
import { ModuleVO } from 'src/app/gen/model/bw/ub/stripehiv/module/vo/module-vo';

@Component({
  selector: 'search-modules',
  templateUrl: './search-modules.component.html',
  styleUrls: ['./search-modules.component.css']
})
export class SearchModulesImplComponent extends SearchModulesComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
    }
	
    afterOnInit() {
    }
    
    doNgAfterViewInit() {
      
    }

    handleFormChanges() {
      
    }

    onNgAfterViewInit() {
    }
}
