// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { SearchModulesSearchComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/web/search/search-modules-search.component';

@Component({
  selector: 'search-modules-search',
  templateUrl: './search-modules-search.component.html',
  styleUrls: ['./search-modules-search.component.css']
})
export class SearchModulesSearchImplComponent extends SearchModulesSearchComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
    
  }


  afterSearchModulesSearch() {    
  }

  doSearchModulesSearch() {
  }
}
