// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { SearchModulesSearchComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/web/search/search-modules-search.component';
import { FormGroup, FormArray, FormControl } from '@angular/forms';

@Component({
  selector: 'search-modules-search',
  templateUrl: './search-modules-search.component.html',
  styleUrls: ['./search-modules-search.component.css']
})
export class SearchModulesSearchImplComponent extends SearchModulesSearchComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
      console.log('SearchModulesSearchImplComponent.beforeOnInit');
      let form = this.getForm();
    }
	
    afterOnInit() {
      console.log('SearchModulesSearchImplComponent.afterOnInit');
      let form = this.getForm();
    }

    doNgAfterViewInit() {
      
    }

    async afterSearchModulesSearch() {let form = this.getForm();
      
      let modulesForm = <FormArray>this.searchModulesForm.get('modules');      
      await this.modules.emit(form.modules);
      console.log(this.searchModulesForm.get('modules'));
    }

    doSearchModulesSearch() {
      
    }
}
