// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 * Generated by hibernate/HibernateEntityImpl.vsl in andromda-hibernate-cartridge on 08/09/2020 10:32:34+0200.
 */
package bw.ub.stripehiv.user;

import bw.ub.stripehiv.role.vo.RoleVO;
import java.util.Collection;

/**
 * @see User
 */
// HibernateEntityImpl.vsl annotations merge-point
public class UserImpl
    extends User
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 875208463312454737L;

    /**
     * @see User#findUsersByRole(RoleVO)
     */
    @Override
    public Collection<User> findUsersByRole(RoleVO role)
    {
        // TODO implement public Collection<User> findUsersByRole(RoleVO role)
        Collection<User> rtn = null;
        return rtn;
    }

// HibernateEntityImpl.vsl merge-point
}