// Generated by hibernate/SpringHibernateDaoImpl.vsl in andromda-spring-cartridge on 07/27/2020 07:46:16+0200.
// license-header java merge-point
/**
 * This is only generated once! It will never be overwritten.
 * You can (and have to!) safely modify it by hand.
 */
package bw.ub.stripehiv.user;

import bw.ub.stripehiv.user.vo.UserSearchCriteria;
import bw.ub.stripehiv.user.vo.UserVO;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.springframework.stereotype.Repository;

/**
 * @see User
 */
@Repository("userDao")
public class UserDaoImpl
    extends UserDaoBase
{
    /**
     * {@inheritDoc}
     */
    @Override
    public void toUserVO(
        User source,
        UserVO target)
    {
        // TODO verify behavior of toUserVO
        super.toUserVO(source, target);
        // WARNING! No conversion for target.dateOfBirth (can't convert source.getDateOfBirth():java.util.Date to java.util.Date
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserVO toUserVO(final User entity)
    {
        // TODO verify behavior of toUserVO
        return super.toUserVO(entity);
    }

    /**
     * Retrieves the entity object that is associated with the specified value object
     * from the object store. If no such entity object exists in the object store,
     * a new, blank entity is created
     */
    private User loadUserFromUserVO(UserVO userVO)
    {
        // TODO implement loadUserFromUserVO
        throw new UnsupportedOperationException("bw.ub.stripehiv.user.loadUserFromUserVO(UserVO) not yet implemented.");

        /* A typical implementation looks like this:
        if (userVO.getId() == null)
        {
            return  User.Factory.newInstance();
        }
        else
        {
            return this.load(userVO.getId());
        }
        */
    }

    /**
     * {@inheritDoc}
     */
    public User userVOToEntity(UserVO userVO)
    {
        // TODO verify behavior of userVOToEntity
        User entity = this.loadUserFromUserVO(userVO);
        this.userVOToEntity(userVO, entity, true);
        return entity;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void userVOToEntity(
        UserVO source,
        User target,
        boolean copyIfNull)
    {
        // TODO verify behavior of userVOToEntity
        super.userVOToEntity(source, target, copyIfNull);
        // No conversion for target.dateOfBirth (can't convert source.getDateOfBirth():java.util.Date to java.util.Date
    }

	@Override
	protected Collection<User> handleFindByCriteria(UserSearchCriteria searchCriteria) throws Exception {
		CriteriaBuilder builder = getSession().getCriteriaBuilder();
		CriteriaQuery<User> query = builder.createQuery(User.class);
		Root<User> root = query.from(User.class);
		List<Predicate> predicates = new ArrayList<Predicate>();

		if (searchCriteria.getEmail() != null) {
			predicates
					.add(builder.equal(root.<String>get("email"), searchCriteria.getEmail()));
		}

		if (searchCriteria.getFirstName() != null) {
			predicates.add(builder.like(root.<String>get("firstName"), "%" + searchCriteria.getFirstName() + "%"));
		}

		if (searchCriteria.getSurname() != null) {
			predicates.add(builder.like(root.<String>get("surname"), "%" + searchCriteria.getSurname() + "%"));
		}

		if (searchCriteria.getUsername() != null) {
			predicates.add(builder.like(root.<String>get("username"), "%" + searchCriteria.getUsername() + "%"));
		}

		if (!predicates.isEmpty()) {
			query.where();
			Predicate[] pr = new Predicate[predicates.size()];
			predicates.toArray(pr);
			query.where(pr);
		}

		query.orderBy(builder.asc(root.get("code")));
		TypedQuery<User> typedQuery = getSession().createQuery(query);
		
		return typedQuery.getResultList();
	}
}