// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package bw.ub.stripehiv.user.web.search;

/**
 * @see bw.ub.stripehiv.user.web.search.UserSearchController
 */
public class UserSearchControllerImpl
    extends UserSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 8232466567595396799L;

    /**
     * @see bw.ub.stripehiv.user.web.search.UserSearchController#doInitialiseSearchScreen(bw.ub.stripehiv.user.vo.UserSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        // populating value with dummy instance
        bw.ub.stripehiv.user.vo.UserSearchCriteria searchCriteria = new bw.ub.stripehiv.user.vo.UserSearchCriteria();
        searchCriteria.setUsername(null);
        searchCriteria.setFirstName(null);
        searchCriteria.setSurname(null);
        searchCriteria.setEmail(null);
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * @see bw.ub.stripehiv.user.web.search.UserSearchController#doUserSearch()
     */
    @Override
    public void doUserSearch()
    {
    }

    /**
     * @see bw.ub.stripehiv.user.web.search.UserSearchController#doEditUser(java.lang.Long id, java.lang.Long userId)
     */
    @Override
    public void doEditUser(DoEditUserForm form)
    {
    }

    /**
     * This dummy variable is used to populate the "users" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final bw.ub.stripehiv.user.vo.UserVO users =
        new bw.ub.stripehiv.user.vo.UserVO
        {
            new bw.ub.stripehiv.user.vo.UserVO(null, "username-1", "firstName-1", "middleName-1", "surname-1", new java.util.Date(), "email-1", "password-1", null, null, null),
            new bw.ub.stripehiv.user.vo.UserVO(null, "username-2", "firstName-2", "middleName-2", "surname-2", new java.util.Date(), "email-2", "password-2", null, null, null),
            new bw.ub.stripehiv.user.vo.UserVO(null, "username-3", "firstName-3", "middleName-3", "surname-3", new java.util.Date(), "email-3", "password-3", null, null, null),
            new bw.ub.stripehiv.user.vo.UserVO(null, "username-4", "firstName-4", "middleName-4", "surname-4", new java.util.Date(), "email-4", "password-4", null, null, null),
            new bw.ub.stripehiv.user.vo.UserVO(null, "username-5", "firstName-5", "middleName-5", "surname-5", new java.util.Date(), "email-5", "password-5", null, null, null)
        };
}