// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { SearchUsersEditComponent } from 'src/app/gen/view/bw/ub/stripehiv/user/web/search/search-users-edit.component';

@Component({
  selector: 'search-users-edit',
  templateUrl: './search-users-edit.component.html',
  styleUrls: ['./search-users-edit.component.css']
})
export class SearchUsersEditImplComponent extends SearchUsersEditComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
    
  }


  afterSearchUsersEdit() {    
  }

  doSearchUsersEdit() {
  }
}
