// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { SearchUsersSearchComponent } from 'src/app/gen/view/bw/ub/stripehiv/user/web/search/search-users-search.component';

@Component({
  selector: 'search-users-search',
  templateUrl: './search-users-search.component.html',
  styleUrls: ['./search-users-search.component.css']
})
export class SearchUsersSearchImplComponent extends SearchUsersSearchComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
    
  }


  afterSearchUsersSearch() {    
  }

  doSearchUsersSearch() {
  }
}
