// Generated by andromda-jsf cartridge (view\table\table.component.impl.ts.vsl) DO NOT EDIT!
import { Component, Injector } from '@angular/core';
import { SearchUsersUsersComponent } from 'src/app/gen/view/bw/ub/stripehiv/user/web/search/search-users-users.component';

@Component({
  selector: 'search-users-users',
  templateUrl: './search-users-users.component.html',
  styleUrls: ['./search-users-users.component.css']
})
export class SearchUsersUsersImplComponent extends SearchUsersUsersComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

	beforeOnInit(){
	}
	
	afterOnInit() {
	}

  doNgAfterViewInit() {
    
  }

}