// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { EditRoleSaveComponent } from 'src/app/gen/view/bw/ub/stripehiv/role/web/edit/edit-role-save.component';
import { EditRoleSaveFormImpl } from 'src/app/gen/form/bw/ub/stripehiv/role/web/edit/edit-role-save-form-impl';

@Component({
  selector: 'edit-role-save',
  templateUrl: './edit-role-save.component.html',
  styleUrls: ['./edit-role-save.component.css']
})
export class EditRoleSaveImplComponent extends EditRoleSaveComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
    console.log(this.editRoleForm);
    
  }
	
  afterOnInit() {
    console.log(this.editRoleForm);
  }

  doNgAfterViewInit() {
    
  }


  afterEditRoleSave() {
    if(localStorage.getItem('editRoleEditRoleSaveForm')) {
      let form: EditRoleSaveFormImpl = JSON.parse(localStorage.getItem('editRoleEditRoleSaveForm'));
      if(form.roleVOSet) {
        this.saveRoleVO.emit(form.roleVO);
      }
    }
  }

  doEditRoleSave() {
    
  }
}
