// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { EditRoleNewComponent } from 'src/app/gen/view/bw/ub/stripehiv/role/web/edit/edit-role-new.component';

@Component({
  selector: 'edit-role-new',
  templateUrl: './edit-role-new.component.html',
  styleUrls: ['./edit-role-new.component.css']
})
export class EditRoleNewImplComponent extends EditRoleNewComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
    
  }


  afterEditRoleNew() {    
  }

  doEditRoleNew() {
  }
}
