// Generated by andromda-jsf cartridge (app.module.ts.vsl) DO NOT EDIT!
// license-header angular merge-point
//
/**
 * @author Generated by app.module.ts.vsl in andromda-anglar-cartridge Do not modify by hand!
 *
 * MODEL CLASS:  $validationName
 */
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, ErrorHandler } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { MatTabsModule} from '@angular/material/tabs';
import { MatTableModule } from '@angular/material/table';
import { MatListModule } from '@angular/material/list';
import { MatSidenavModule } from '@angular/material/sidenav';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatMenuModule } from '@angular/material/menu';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatSelectModule } from '@angular/material/select';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { MatPaginatorModule } from '@angular/material/paginator';
import { MatDialogModule } from '@angular/material/dialog';
import { MatNativeDateModule, MatRippleModule } from '@angular/material/core';
import { MatSortModule } from '@angular/material/sort';
import { MatTooltipModule } from '@angular/material/tooltip';
import { NgForm } from '@angular/forms';
import { NgIdleKeepaliveModule } from '@ng-idle/keepalive';
import { MomentModule } from 'angular2-moment';
import { ModalModule } from 'ngx-bootstrap/modal';
import { RequestOptions } from '@angular/http';
import { RxReactiveFormsModule } from '@rxweb/reactive-form-validators';

import { StripehivLayoutComponent } from './layout/stripehiv-layout.component';
import { StripehivHeaderComponent } from './header/stripehiv-header.component';
import { StripehivNavigationComponent } from './navigation/stripehiv-navigation.component';
import { StripehivRoutingModule } from './stripehiv-routing.module';
import { StripehivComponent } from './stripehiv.component';

import { ObjectiveServiceImpl } from './impl/service/bw/ub/stripehiv/module/objective/service/objective-service-impl';
import { ModuleServiceImpl } from './impl/service/bw/ub/stripehiv/module/service/module-service-impl';

import { ObjectiveSearchControllerImpl } from './impl/controller/bw/ub/stripehiv/module/objective/web/search/objective-search-controller-impl';
import { ObjectiveEditControllerImpl } from './impl/controller/bw/ub/stripehiv/module/objective/web/edit/objective-edit-controller-impl';
import { ModuleSearchControllerImpl } from './impl/controller/bw/ub/stripehiv/module/web/search/module-search-controller-impl';
import { ModuleEditControllerImpl } from './impl/controller/bw/ub/stripehiv/module/web/edit/module-edit-controller-impl';

import { EditObjectiveImplComponent } from './impl/view/bw/ub/stripehiv/module/objective/web/edit/edit-objective.impl.component';
import { SearchModulesImplComponent } from './impl/view/bw/ub/stripehiv/module/web/search/search-modules.impl.component';
import { EditModuleImplComponent } from './impl/view/bw/ub/stripehiv/module/web/edit/edit-module.impl.component';
import { SearchObjectivesImplComponent } from './impl/view/bw/ub/stripehiv/module/objective/web/search/search-objectives.impl.component';

import { SearchModulesModulesImplComponent } from './impl/view/bw/ub/stripehiv/module/web/search/search-modules-modules.impl.component';
import { SearchObjectivesObjectivesImplComponent } from './impl/view/bw/ub/stripehiv/module/objective/web/search/search-objectives-objectives.impl.component';

import { EditObjectiveNewImplComponent } from './impl/view//bw/ub/stripehiv/module/objective/web/edit/edit-objective-new.impl.component';
import { EditModuleNewImplComponent } from './impl/view//bw/ub/stripehiv/module/web/edit/edit-module-new.impl.component';
import { SearchModulesSearchImplComponent } from './impl/view//bw/ub/stripehiv/module/web/search/search-modules-search.impl.component';
import { EditModuleSaveImplComponent } from './impl/view//bw/ub/stripehiv/module/web/edit/edit-module-save.impl.component';
import { SearchObjectivesSearchImplComponent } from './impl/view//bw/ub/stripehiv/module/objective/web/search/search-objectives-search.impl.component';
import { EditObjectiveSaveImplComponent } from './impl/view//bw/ub/stripehiv/module/objective/web/edit/edit-objective-save.impl.component';

import { ModuleSearchCriteria } from './gen/model/bw/ub/stripehiv/module/vo/module-search-criteria';
import { ObjectiveVO } from './gen/model/bw/ub/stripehiv/module/objective/vo/objective-vo';
import { ObjectiveSearchCriteria } from './gen/model/bw/ub/stripehiv/module/objective/vo/objective-search-criteria';
import { ModuleVO } from './gen/model/bw/ub/stripehiv/module/vo/module-vo';

@NgModule({
    declarations: [
        StripehivComponent,
        StripehivLayoutComponent,
        StripehivHeaderComponent,
        StripehivNavigationComponent,

        EditObjectiveImplComponent,
        SearchModulesImplComponent,
        EditModuleImplComponent,
        SearchObjectivesImplComponent,

        SearchModulesModulesImplComponent,
        SearchObjectivesObjectivesImplComponent,

        EditObjectiveNewImplComponent,
        EditModuleNewImplComponent,
        SearchModulesSearchImplComponent,
        EditModuleSaveImplComponent,
        SearchObjectivesSearchImplComponent,
        EditObjectiveSaveImplComponent

    ],
    imports: [
        CommonModule,
        MatButtonModule,
        MatCheckboxModule,
        MatDatepickerModule,
        MatDialogModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatMenuModule,
        MatNativeDateModule,
        MatPaginatorModule,
        MatRippleModule,
        MatSelectModule,
        MatSidenavModule,
        MatSortModule,
        MatTableModule,
        MatTabsModule,
        MatToolbarModule,
        MatTooltipModule,
        BrowserModule,
        BrowserAnimationsModule,
        HttpClientModule,
        FormsModule,
        ReactiveFormsModule,
        RxReactiveFormsModule,
        NgIdleKeepaliveModule.forRoot(),
        MomentModule,
        ModalModule.forRoot(),
        StripehivRoutingModule
    ],
    exports: [
        MatButtonModule,
        MatCheckboxModule,
        MatDatepickerModule,
        MatDialogModule,
        MatIconModule,
        MatInputModule,
        MatListModule,
        MatMenuModule,
        MatNativeDateModule,
        MatPaginatorModule,
        MatRippleModule,
        MatSelectModule,
        MatSidenavModule,
        MatSortModule,
        MatTableModule,
        MatTabsModule,
        MatToolbarModule,
        MatTooltipModule
    ],
    providers: [
        ModuleSearchCriteria,
        ObjectiveVO,
        ObjectiveSearchCriteria,
        ModuleVO,

        ObjectiveServiceImpl,
        ModuleServiceImpl,

        ObjectiveSearchControllerImpl,
        ObjectiveEditControllerImpl,
        ModuleSearchControllerImpl,
        ModuleEditControllerImpl,

        EditObjectiveImplComponent,
        SearchModulesImplComponent,
        EditModuleImplComponent,
        SearchObjectivesImplComponent,

        SearchModulesModulesImplComponent,
        SearchObjectivesObjectivesImplComponent,

        EditObjectiveNewImplComponent,
        EditModuleNewImplComponent,
        SearchModulesSearchImplComponent,
        EditModuleSaveImplComponent,
        SearchObjectivesSearchImplComponent,
        EditObjectiveSaveImplComponent

    ],
    bootstrap: [StripehivComponent]
})
export class StripehivModule { }
