// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { SearchRolesComponent } from 'src/app/gen/view/bw/ub/stripehiv/role/web/search/search-roles.component';

@Component({
  selector: 'search-roles',
  templateUrl: './search-roles.component.html',
  styleUrls: ['./search-roles.component.css']
})
export class SearchRolesImplComponent extends SearchRolesComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
    }
	
    afterOnInit() {
    }

    doNgAfterViewInit() {
      
    }

    handleFormChanges(change: any) {
    }
}
