// Generated by andromda-jsf cartridge (view\table\table.component.impl.ts.vsl) DO NOT EDIT!
import { Component, Injector } from '@angular/core';
import { SearchRolesRolesComponent } from 'src/app/gen/view/bw/ub/stripehiv/role/web/search/search-roles-roles.component';

@Component({
  selector: 'search-roles-roles',
  templateUrl: './search-roles-roles.component.html',
  styleUrls: ['./search-roles-roles.component.css']
})
export class SearchRolesRolesImplComponent extends SearchRolesRolesComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

	beforeOnInit(){
	}
	
	afterOnInit() {
	}

  doNgAfterViewInit() {
    
  }


	doSearchRolesEdit(id: number): any {
	}
}