// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { SearchRolesSearchComponent } from 'src/app/gen/view/bw/ub/stripehiv/role/web/search/search-roles-search.component';

@Component({
  selector: 'search-roles-search',
  templateUrl: './search-roles-search.component.html',
  styleUrls: ['./search-roles-search.component.css']
})
export class SearchRolesSearchImplComponent extends SearchRolesSearchComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
    
  }


  afterSearchRolesSearch() {    
  }

  doSearchRolesSearch() {
  }
}
