// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { SearchObjectivesSearchComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/objective/web/search/search-objectives-search.component';

@Component({
  selector: 'search-objectives-search',
  templateUrl: './search-objectives-search.component.html',
  styleUrls: ['./search-objectives-search.component.css']
})
export class SearchObjectivesSearchImplComponent extends SearchObjectivesSearchComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
    
  }


  afterSearchObjectivesSearch() {    
  }

  doSearchObjectivesSearch() {
  }
}
