// Generated by andromda-jsf cartridge (view\table\table.component.impl.ts.vsl) DO NOT EDIT!
import { Component, Injector } from '@angular/core';
import { SearchObjectivesObjectivesComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/objective/web/search/search-objectives-objectives.component';

@Component({
  selector: 'search-objectives-objectives',
  templateUrl: './search-objectives-objectives.component.html',
  styleUrls: ['./search-objectives-objectives.component.css']
})
export class SearchObjectivesObjectivesImplComponent extends SearchObjectivesObjectivesComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

	beforeOnInit(){
	}
	
	afterOnInit() {
	}

  doNgAfterViewInit() {
    
  }


	doSearchObjectivesEdit(id: number): any {
	}
}