// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { SearchObjectivesComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/objective/web/search/search-objectives.component';

@Component({
  selector: 'search-objectives',
  templateUrl: './search-objectives.component.html',
  styleUrls: ['./search-objectives.component.css']
})
export class SearchObjectivesImplComponent extends SearchObjectivesComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
    }
	
    afterOnInit() {
    }

    doNgAfterViewInit() {
      
    }

    handleFormChanges(change: any) {
    }
}
