// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package bw.ub.stripehiv.module.web.edit;

/**
 * @see bw.ub.stripehiv.module.web.edit.ModuleEditController
 */
public class ModuleEditControllerImpl
    extends ModuleEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -3214850665893502825L;

    /**
     * @see bw.ub.stripehiv.module.web.edit.ModuleEditController#doInitialiseEditScreen(java.lang.Long id)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
    }

    /**
     * @see bw.ub.stripehiv.module.web.edit.ModuleEditController#doNewModule()
     */
    @Override
    public void doNewModule()
    {
    }

    /**
     * @see bw.ub.stripehiv.module.web.edit.ModuleEditController#doSaveModule()
     */
    @Override
    public void doSaveModule()
    {
    }

}