// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { EditObjectiveSaveComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/objective/web/edit/edit-objective-save.component';

@Component({
  selector: 'edit-objective-save',
  templateUrl: './edit-objective-save.component.html',
  styleUrls: ['./edit-objective-save.component.css']
})
export class EditObjectiveSaveImplComponent extends EditObjectiveSaveComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
    
  }


  afterEditObjectiveSave() {    
  }

  doEditObjectiveSave() {
  }
}
