// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { EditObjectiveNewComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/objective/web/edit/edit-objective-new.component';

@Component({
  selector: 'edit-objective-new',
  templateUrl: './edit-objective-new.component.html',
  styleUrls: ['./edit-objective-new.component.css']
})
export class EditObjectiveNewImplComponent extends EditObjectiveNewComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
    
  }


  afterEditObjectiveNew() {    
  }

  doEditObjectiveNew() {
  }
}
