// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { EditObjectiveComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/objective/web/edit/edit-objective.component';

@Component({
  selector: 'edit-objective',
  templateUrl: './edit-objective.component.html',
  styleUrls: ['./edit-objective.component.css']
})
export class EditObjectiveImplComponent extends EditObjectiveComponent {

    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
    }
	
    afterOnInit() {
    }

    doNgAfterViewInit() {
      
    }

    handleFormChanges(change: any) {
    }
}
