// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package bw.ub.stripehiv.module.objective.web.edit;

/**
 * @see bw.ub.stripehiv.module.objective.web.edit.ObjectiveEditController
 */
public class ObjectiveEditControllerImpl
    extends ObjectiveEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -5164449171410178487L;

    /**
     * @see bw.ub.stripehiv.module.objective.web.edit.ObjectiveEditController#doInitialiseEditScreen(java.lang.Long id)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
    }

    /**
     * @see bw.ub.stripehiv.module.objective.web.edit.ObjectiveEditController#doNewObjective()
     */
    @Override
    public void doNewObjective()
    {
    }

    /**
     * @see bw.ub.stripehiv.module.objective.web.edit.ObjectiveEditController#doSaveObjective()
     */
    @Override
    public void doSaveObjective()
    {
    }

}