// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { EditUserSaveComponent } from 'src/app/gen/view/bw/ub/stripehiv/user/web/edit/edit-user-save.component';

@Component({
  selector: 'edit-user-save',
  templateUrl: './edit-user-save.component.html',
  styleUrls: ['./edit-user-save.component.css']
})
export class EditUserSaveImplComponent extends EditUserSaveComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
    
  }


  afterEditUserSave() {    
  }

  doEditUserSave() {
  }
}
