// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { EditUserNewComponent } from 'src/app/gen/view/bw/ub/stripehiv/user/web/edit/edit-user-new.component';

@Component({
  selector: 'edit-user-new',
  templateUrl: './edit-user-new.component.html',
  styleUrls: ['./edit-user-new.component.css']
})
export class EditUserNewImplComponent extends EditUserNewComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
    
  }


  afterEditUserNew() {    
  }

  doEditUserNew() {
  }
}
