// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package bw.ub.stripehiv.module.web.search;

/**
 * @see bw.ub.stripehiv.module.web.search.ModuleSearchController
 */
public class ModuleSearchControllerImpl
    extends ModuleSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 4342854548231820430L;

    /**
     * @see bw.ub.stripehiv.module.web.search.ModuleSearchController#doInitialiseSearchScreen(bw.ub.stripehiv.module.vo.ModuleSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        // populating value with dummy instance
        bw.ub.stripehiv.module.vo.ModuleSearchCriteria searchCriteria = new bw.ub.stripehiv.module.vo.ModuleSearchCriteria();
        searchCriteria.setCode(null);
        searchCriteria.setModuleName(null);
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * @see bw.ub.stripehiv.module.web.search.ModuleSearchController#doModuleSearch()
     */
    @Override
    public void doModuleSearch()
    {
    	
    }

    /**
     * @see bw.ub.stripehiv.module.web.search.ModuleSearchController#doEditModule(java.lang.Long id, java.lang.Long moduleId)
     */
    @Override
    public void doEditModule(DoEditModuleForm form)
    {
    }

    /**
     * This dummy variable is used to populate the "modules" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final bw.ub.stripehiv.module.vo.ModuleVO[] modules =
        {
            new bw.ub.stripehiv.module.vo.ModuleVO(null, "code-1", "moduleName-1", "description-1", null, null, null, null),
            new bw.ub.stripehiv.module.vo.ModuleVO(null, "code-2", "moduleName-2", "description-2", null, null, null, null),
            new bw.ub.stripehiv.module.vo.ModuleVO(null, "code-3", "moduleName-3", "description-3", null, null, null, null),
            new bw.ub.stripehiv.module.vo.ModuleVO(null, "code-4", "moduleName-4", "description-4", null, null, null, null),
            new bw.ub.stripehiv.module.vo.ModuleVO(null, "code-5", "moduleName-5", "description-5", null, null, null, null)
        };
}