// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package bw.ub.stripehiv.role.web.search;

/**
 * @see bw.ub.stripehiv.role.web.search.RoleSearchController
 */
public class RoleSearchControllerImpl
    extends RoleSearchController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = 1318516161011473110L;

    /**
     * @see bw.ub.stripehiv.role.web.search.RoleSearchController#doInitialiseSearchScreen(bw.ub.stripehiv.role.vo.RoleSearchCriteria searchCriteria)
     */
    @Override
    public void doInitialiseSearchScreen(DoInitialiseSearchScreenForm form)
    {
        // populating value with dummy instance
        bw.ub.stripehiv.role.vo.RoleSearchCriteria searchCriteria = new bw.ub.stripehiv.role.vo.RoleSearchCriteria();
        searchCriteria.setCode(null);
        searchCriteria.setUser(null);
        form.setSearchCriteria(searchCriteria);
    }

    /**
     * @see bw.ub.stripehiv.role.web.search.RoleSearchController#doRoleSearch()
     */
    @Override
    public void doRoleSearch()
    {
    }

    /**
     * @see bw.ub.stripehiv.role.web.search.RoleSearchController#doEditRole(java.lang.Long id, java.lang.Long roleId)
     */
    @Override
    public void doEditRole(DoEditRoleForm form)
    {
    }

    /**
     * This dummy variable is used to populate the "roles" table.
     * You may delete it when you add you own code in this controller.
     */
    private static final bw.ub.stripehiv.role.vo.RoleVO roles =
        new bw.ub.stripehiv.role.vo.RoleVO
        {
            new bw.ub.stripehiv.role.vo.RoleVO(null, null, "description-1", null),
            new bw.ub.stripehiv.role.vo.RoleVO(null, null, "description-2", null),
            new bw.ub.stripehiv.role.vo.RoleVO(null, null, "description-3", null),
            new bw.ub.stripehiv.role.vo.RoleVO(null, null, "description-4", null),
            new bw.ub.stripehiv.role.vo.RoleVO(null, null, "description-5", null)
        };
}