// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { EditModuleSaveComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/web/edit/edit-module-save.component';
import { ModuleStatus } from 'src/app/gen/model/bw/ub/stripehiv/module/module-status';

@Component({
  selector: 'edit-module-save',
  templateUrl: './edit-module-save.component.html',
  styleUrls: ['./edit-module-save.component.css']
})
export class EditModuleSaveImplComponent extends EditModuleSaveComponent {

  status = ModuleStatus;
  public statusOptions = [];

  constructor(private injector: Injector) {
      super(injector);
      this.statusOptions = Object.keys(this.status);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
    this.moduleService.getAllModules().subscribe(
      results => {
        this.moduleVONextModuleBackingList = results;
        this.moduleVOPreviousModuleBackingList = results;
      }
    );
  }

  doEditModuleSave() {
  }

  afterEditModuleSave() {
  }

  doNgAfterViewInit() {
    let form = JSON.parse(localStorage.getItem('searchModulesSearchModulesEditForm'));
      this.moduleService.findById(form.id).subscribe(
        data => {
          console.log(data);
          this.moduleVO.emit(data);
        }
      );
  }
}
