// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { EditModuleNewComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/web/edit/edit-module-new.component';

@Component({
  selector: 'edit-module-new',
  templateUrl: './edit-module-new.component.html',
  styleUrls: ['./edit-module-new.component.css']
})
export class EditModuleNewImplComponent extends EditModuleNewComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
    
  }


  afterEditModuleNew() {    
  }

  doEditModuleNew() {
  }
}
