// Generated by andromda-angular cartridge (view\action\view.action.impl.ts.vsl) DO NOT EDIT! -->
import { Component, Injector } from '@angular/core';
import { EditModuleSaveComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/web/edit/edit-module-save.component';
import { EditModuleSaveFormImpl } from 'src/app/gen/form/bw/ub/stripehiv/module/web/edit/edit-module-save-form-impl';
import { ModuleVO } from 'src/app/gen/model/bw/ub/stripehiv/module/vo/module-vo';

@Component({
  selector: 'edit-module-save',
  templateUrl: './edit-module-save.component.html',
  styleUrls: ['./edit-module-save.component.css']
})
export class EditModuleSaveImplComponent extends EditModuleSaveComponent {

  constructor(private injector: Injector) {
      super(injector);
  }

  beforeOnInit(){
    if(localStorage.getItem('moduleVOBackingList')) 
    {
      console.log(localStorage.getItem('moduleVOBackingList'));

      this.moduleService.getAllModules().subscribe(
        result => {
          this.moduleVOBackingList = result;
          this.moduleVONextModuleBackingList = this.moduleVOBackingList;
          this.moduleVOPreviousModuleBackingList = this.moduleVOBackingList;
        }
      );
    }
  }
	
  afterOnInit() {
  }

  doNgAfterViewInit() {
  }


  afterEditModuleSave() {   
    let form: EditModuleSaveFormImpl = JSON.parse(localStorage.getItem('editModuleEditModuleSaveForm')); 
    this.saveModuleVO.emit(form.moduleVO);
    this.moduleVOBackingList.push(form.moduleVO);
    //this.moduleVOPreviousModuleBackingList.push(form.moduleVO);
  }

  doEditModuleSave() {
  }

  editModuleNew() {
    this.saveModuleVO.emit(new ModuleVO());
  }
}
