// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component, Injector } from '@angular/core';
import { EditModuleComponent } from 'src/app/gen/view/bw/ub/stripehiv/module/web/edit/edit-module.component';

@Component({
  selector: 'edit-module',
  templateUrl: './edit-module.component.html',
  styleUrls: ['./edit-module.component.css']
})
export class EditModuleImplComponent extends EditModuleComponent {
    constructor(private injector: Injector) {
        super(injector);
    }

    beforeOnInit(){
    }
	
    afterOnInit() {
    }

    handleFormChanges() {
    }

    doNgAfterViewInit() {
      
    }

}
