// license-header java merge-point
// Generated by andromda-jsf cartridge (controllers\ControllerImpl.java.vsl)
package bw.ub.stripehiv.role.web.edit;

/**
 * @see bw.ub.stripehiv.role.web.edit.RoleEditController
 */
public class RoleEditControllerImpl
    extends RoleEditController
{
    /**
     * The serial version UID of this class. Needed for serialization.
     */
    private static final long serialVersionUID = -7015155698935580659L;

    /**
     * @see bw.ub.stripehiv.role.web.edit.RoleEditController#doInitialiseEditScreen(java.lang.Long id)
     */
    @Override
    public void doInitialiseEditScreen(DoInitialiseEditScreenForm form)
    {
    }

    /**
     * @see bw.ub.stripehiv.role.web.edit.RoleEditController#doNewRole()
     */
    @Override
    public void doNewRole()
    {
    }

    /**
     * @see bw.ub.stripehiv.role.web.edit.RoleEditController#doSaveRole()
     */
    @Override
    public void doSaveRole()
    {
    }

}